# Generated by Django 4.0.5 on 2022-12-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('second_date_from', models.DateTimeField()),
                ('second_date_to', models.DateTimeField()),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('kecamatan', models.CharField(max_length=256)),
                ('kabupaten', models.CharField(max_length=256)),
                ('provinsi', models.CharField(max_length=256)),
                ('contacts', models.TextField()),
                ('image', models.BinaryField()),
            ],
        ),
    ]
