# Generated by Django 4.0.5 on 2022-12-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_name_user_username_user_is_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=True, verbose_name='Is User'),
        ),
    ]
