# Generated by Django 4.0.5 on 2022-12-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_detailuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailuser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='DetailUser',
        ),
    ]
