# Generated by Django 4.0.5 on 2022-12-20 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailuser',
            old_name='relate_user_id',
            new_name='user_ptr',
        ),
    ]
