# Generated by Django 4.0.5 on 2022-12-20 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_rename_relate_user_id_detailuser_user_ptr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailUser',
        ),
    ]
