# Generated by Django 4.0.5 on 2022-12-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailuser',
            old_name='related_user_id',
            new_name='related_user',
        ),
    ]
