# Generated by Django 4.0.5 on 2023-01-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_rename_related_user_id_detailuser_related_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractDetailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_user', models.BooleanField(default=True, verbose_name='Is User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
